version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cobit2019_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: develovers
      POSTGRES_DB: cobit2019
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
